"""
DL-Predicted KRAS Allele-Stratified Survival Curves
----------------------------------------------------
Source: f:\ADDS\data\pritamab_synthetic_cohort.csv
        (Generated by Pritamab Multimodal Fusion MLP, n=1,000)

Layout: 2 rows × 5 cols (PFS / OS per KRAS allele)
        + bottom row: summary mPFS/mOS/ORR comparison
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D

plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "axes.facecolor": "#F7F9FC",
    "axes.edgecolor": "#CBD5E0",
    "axes.labelcolor": "#2D3748",
    "xtick.color": "#4A5568",
    "ytick.color": "#4A5568",
    "text.color": "#2D3748",
    "grid.color": "#E2E8F0",
    "grid.linestyle": "--",
    "grid.alpha": 0.7,
})

BG    = "#FFFFFF"
NAVY  = "#1A365D"
RED   = "#C0392B"
GREEN = "#276749"
BLUE  = "#1A6FBA"
PURP  = "#6B46C1"
TEAL  = "#2C7A7B"
GRAY  = "#718096"
GOLD  = "#B7700D"

ALLELE_INFO = [
    ("G12D", GREEN, "Most prevalent (26%), highest PrPc coupling"),
    ("G12V", BLUE,  "2nd most prevalent (19%)"),
    ("G12C", PURP,  "12% — Sotorasib triple therapy eligible"),
    ("G13D", TEAL,  "9% — Moderate Pritamab response"),
    ("WT",   GRAY,  "34% — PrPc-high patient selection critical"),
]

# ── Load DL synthetic data ─────────────────────────────────────────────────
CSV = r"f:\ADDS\data\pritamab_synthetic_cohort.csv"
df  = pd.read_csv(CSV)
print(f"Loaded: {len(df)} patients, arms: {df['arm'].value_counts().to_dict()}")

# ── KM helpers ─────────────────────────────────────────────────────────────
def km(t, e, t_max=None):
    if len(t) == 0: return np.array([0, 1]), np.array([1.0, 1.0])
    if t_max is None: t_max = t.max()
    idx = np.argsort(t)
    ts, es = t[idx], e[idx]
    nar = len(ts); S = 1.0
    ks, ss = [0], [1.0]
    for ti, ei in zip(ts, es):
        if ei: S *= (1 - 1/max(nar, 1))
        nar -= 1
        ks.append(ti); ss.append(S)
    ks.append(max(t_max, ks[-1])); ss.append(ss[-1])
    return np.array(ks), np.array(ss)

def med_km(ts, ss):
    cross = np.where(np.array(ss) <= 0.5)[0]
    return ts[cross[0]] if len(cross) else np.nan

def logrank_p_simple(t1, e1, t2, e2):
    import math
    all_t = np.concatenate([t1, t2]); all_e = np.concatenate([e1, e2])
    ev_ts = np.unique(all_t[all_e == 1])
    O1=O2=E1=E2=0.0
    for ev in ev_ts:
        n1=np.sum(t1>=ev); n2=np.sum(t2>=ev); nt=n1+n2
        if nt==0: continue
        d1=np.sum((t1==ev)&(e1==1)); d2=np.sum((t2==ev)&(e2==1)); d=d1+d2
        O1+=d1; O2+=d2; E1+=d*n1/nt; E2+=d*n2/nt
    if E1==0 or E2==0: return 1.0
    chi2 = (O1-E1)**2/max(E1,1e-6) + (O2-E2)**2/max(E2,1e-6)
    return round(max(min(1 - math.exp(-0.5*chi2), 1.0), 0.001), 4)

# ── Figure layout ──────────────────────────────────────────────────────────
fig = plt.figure(figsize=(28, 20), facecolor=BG)
gs  = gridspec.GridSpec(3, 5, figure=fig,
                         left=0.055, right=0.975,
                         top=0.895,  bottom=0.055,
                         hspace=0.55, wspace=0.28)

# Title banner
tbar = fig.add_axes([0, 0.920, 1, 0.080], facecolor=NAVY)
tbar.axis("off")
tbar.text(0.5, 0.64,
          "KRAS Allele-Stratified Survival  ·  DL Multimodal Fusion MLP Predictions",
          ha="center", va="center", fontsize=18, fontweight="bold",
          color="white", transform=tbar.transAxes)
tbar.text(0.5, 0.14,
          f"n={len(df)} AI-generated patients  (Cellpose 128d + RNA-seq 256d + PK/PD 32d + CT 64d → Fusion MLP)  "
          f"|  Stratified by KRAS allele (G12D/G12V/G12C/G13D/WT)  "
          f"|  Pritamab (blue solid) vs Standard Chemo (red dashed)",
          ha="center", va="center", fontsize=9.5, color="#BEE3F8",
          transform=tbar.transAxes)

T_MAX = 40  # months
summary = []  # for panel row 3

for col_i, (allele, clr, note) in enumerate(ALLELE_INFO):
    sub = df[df["kras_allele"] == allele]
    sp  = sub[sub["arm"] == "Pritamab"]
    sc  = sub[sub["arm"] == "Control"]

    n_p = len(sp); n_c = len(sc)

    # ── Row 0: PFS ─────────────────────────────────────────────────────────
    ax_pfs = fig.add_subplot(gs[0, col_i])
    ax_pfs.set_facecolor("#F7F9FC")
    ax_pfs.grid(True, axis="y")

    tp_p = sp["pfs_months"].values; ep_p = sp["pfs_event"].values
    tp_c = sc["pfs_months"].values; ep_c = sc["pfs_event"].values

    ts_p, ss_p = km(tp_p, ep_p, T_MAX)
    ts_c, ss_c = km(tp_c, ep_c, T_MAX)
    med_p_pfs  = med_km(ts_p, ss_p)
    med_c_pfs  = med_km(ts_c, ss_c)
    pv_pfs     = logrank_p_simple(tp_p, ep_p, tp_c, ep_c)
    hr_pfs     = (med_c_pfs / med_p_pfs) if (med_p_pfs and not np.isnan(med_p_pfs)) else 1.0

    ax_pfs.step(ts_c, ss_c, where="post", color=RED,  lw=2.0, linestyle="dashed")
    ax_pfs.step(ts_p, ss_p, where="post", color=clr,  lw=2.5, linestyle="solid")
    _tg = np.linspace(0, T_MAX, 300)
    _sp = np.interp(_tg, ts_p, ss_p)
    _sc = np.interp(_tg, ts_c, ss_c)
    ax_pfs.fill_between(_tg, _sp, _sc, alpha=0.07, color=clr)
    ax_pfs.axhline(0.5, color=GRAY, lw=0.7, linestyle="--", alpha=0.5)

    # Median annotation
    if not np.isnan(med_p_pfs):
        ax_pfs.axvline(med_p_pfs, color=clr, lw=0.7, alpha=0.35, linestyle=":")
    if not np.isnan(med_c_pfs):
        ax_pfs.axvline(med_c_pfs, color=RED,  lw=0.7, alpha=0.35, linestyle=":")

    pstr = f"p={pv_pfs:.3f}" if pv_pfs >= 0.001 else "p<0.001"
    med_p_str = f"{med_p_pfs:.1f}m" if not np.isnan(med_p_pfs) else "NR"
    med_c_str = f"{med_c_pfs:.1f}m" if not np.isnan(med_c_pfs) else "NR"

    ax_pfs.text(0.97, 0.97,
                f"HR={hr_pfs:.2f}\n{pstr}",
                ha="right", va="top", fontsize=9, color=clr, fontweight="bold",
                transform=ax_pfs.transAxes,
                bbox=dict(boxstyle="round,pad=0.3", facecolor="white",
                          edgecolor=clr, alpha=0.90, linewidth=1.0))
    ax_pfs.text(0.03, 0.05,
                f"Prit: {med_p_str}\nCtrl: {med_c_str}",
                ha="left", va="bottom", fontsize=8.5, color="#2D3748",
                transform=ax_pfs.transAxes,
                bbox=dict(boxstyle="round,pad=0.25", facecolor="#F0F4F8",
                          edgecolor="none"))

    ax_pfs.set_xlim(0, T_MAX); ax_pfs.set_ylim(0, 1.08)
    ax_pfs.set_title(f"KRAS {allele}  (PFS)\n"
                     f"P n={n_p}  |  C n={n_c}",
                     fontsize=11, fontweight="bold",
                     color=clr if allele != "WT" else GRAY, pad=7)
    ax_pfs.set_xlabel("Months", fontsize=9)
    if col_i == 0: ax_pfs.set_ylabel("PFS Probability", fontsize=10)
    ax_pfs.spines[["top","right"]].set_visible(False)
    ax_pfs.tick_params(labelsize=8.5)

    # ── Row 1: OS ──────────────────────────────────────────────────────────
    ax_os = fig.add_subplot(gs[1, col_i])
    ax_os.set_facecolor("#F7F9FC")
    ax_os.grid(True, axis="y")

    to_p = sp["os_months"].values; eo_p = sp["os_event"].values
    to_c = sc["os_months"].values; eo_c = sc["os_event"].values

    ts_op, ss_op = km(to_p, eo_p, T_MAX)
    ts_oc, ss_oc = km(to_c, eo_c, T_MAX)
    med_p_os  = med_km(ts_op, ss_op)
    med_c_os  = med_km(ts_oc, ss_oc)
    pv_os     = logrank_p_simple(to_p, eo_p, to_c, eo_c)
    hr_os     = (med_c_os / med_p_os) if (med_p_os and not np.isnan(med_p_os)) else 1.0

    ax_os.step(ts_oc, ss_oc, where="post", color=RED,  lw=2.0, linestyle="dashed")
    ax_os.step(ts_op, ss_op, where="post", color=clr,  lw=2.5, linestyle="solid")
    _tg2 = np.linspace(0, T_MAX, 300)
    _sop = np.interp(_tg2, ts_op, ss_op)
    _soc = np.interp(_tg2, ts_oc, ss_oc)
    ax_os.fill_between(_tg2, _sop, _soc, alpha=0.07, color=clr)
    ax_os.axhline(0.5, color=GRAY, lw=0.7, linestyle="--", alpha=0.5)

    if not np.isnan(med_p_os): ax_os.axvline(med_p_os, color=clr, lw=0.7, alpha=0.35, linestyle=":")
    if not np.isnan(med_c_os): ax_os.axvline(med_c_os, color=RED,  lw=0.7, alpha=0.35, linestyle=":")

    pstr_os = f"p={pv_os:.3f}" if pv_os >= 0.001 else "p<0.001"
    med_op_str = f"{med_p_os:.1f}m" if not np.isnan(med_p_os) else "NR"
    med_oc_str = f"{med_c_os:.1f}m" if not np.isnan(med_c_os) else "NR"

    ax_os.text(0.97, 0.97,
               f"HR={hr_os:.2f}\n{pstr_os}",
               ha="right", va="top", fontsize=9, color=clr, fontweight="bold",
               transform=ax_os.transAxes,
               bbox=dict(boxstyle="round,pad=0.3", facecolor="white",
                         edgecolor=clr, alpha=0.90, linewidth=1.0))
    ax_os.text(0.03, 0.05,
               f"Prit: {med_op_str}\nCtrl: {med_oc_str}",
               ha="left", va="bottom", fontsize=8.5, color="#2D3748",
               transform=ax_os.transAxes,
               bbox=dict(boxstyle="round,pad=0.25", facecolor="#F0F4F8",
                         edgecolor="none"))

    ax_os.set_xlim(0, T_MAX); ax_os.set_ylim(0, 1.08)
    ax_os.set_title(f"KRAS {allele}  (OS)\n"
                    f"P n={n_p}  |  C n={n_c}",
                    fontsize=11, fontweight="bold",
                    color=clr if allele != "WT" else GRAY, pad=7)
    ax_os.set_xlabel("Months", fontsize=9)
    if col_i == 0: ax_os.set_ylabel("OS Probability", fontsize=10)
    ax_os.spines[["top","right"]].set_visible(False)
    ax_os.tick_params(labelsize=8.5)

    # Accumulate summary
    orr_p_a = sp["orr"].mean() * 100 if n_p else 0
    orr_c_a = sc["orr"].mean() * 100 if n_c else 0
    syn_p   = sp["synergy_score"].mean() if n_p else 0
    summary.append({
        "allele": allele, "color": clr,
        "med_pfs_p": med_p_pfs if not np.isnan(med_p_pfs) else 0,
        "med_pfs_c": med_c_pfs if not np.isnan(med_c_pfs) else 0,
        "med_os_p":  med_p_os  if not np.isnan(med_p_os)  else 0,
        "med_os_c":  med_c_os  if not np.isnan(med_c_os)  else 0,
        "hr_pfs": hr_pfs, "hr_os": hr_os,
        "orr_p": orr_p_a, "orr_c": orr_c_a,
        "syn_p": syn_p, "n_p": n_p, "n_c": n_c,
        "note": note,
    })

# ── Row 2: Summary ─────────────────────────────────────────────────────────
ax_sum = fig.add_subplot(gs[2, :])
ax_sum.set_facecolor("#F7F9FC")
ax_sum.grid(True, axis="y", zorder=0)
ax2_sum = ax_sum.twinx()

x  = np.arange(len(summary))
w  = 0.20
al_names = [s["allele"] for s in summary]
clrs     = [s["color"]  for s in summary]

b_pfs_p = ax_sum.bar(x - 1.5*w, [s["med_pfs_p"] for s in summary],
                      w, color=clrs, alpha=0.90, edgecolor="white",
                      label="mPFS Pritamab", zorder=3)
b_pfs_c = ax_sum.bar(x - 0.5*w, [s["med_pfs_c"] for s in summary],
                      w, color=clrs, alpha=0.40, hatch="//", edgecolor="white",
                      label="mPFS Control", zorder=3)
b_os_p  = ax_sum.bar(x + 0.5*w, [s["med_os_p"] for s in summary],
                      w, color=clrs, alpha=0.65, edgecolor="white",
                      label="mOS Pritamab", zorder=3)
b_os_c  = ax_sum.bar(x + 1.5*w, [s["med_os_c"] for s in summary],
                      w, color=clrs, alpha=0.30, hatch="xx", edgecolor="white",
                      label="mOS Control", zorder=3)

# Value labels
for bars, vals in [(b_pfs_p, [s["med_pfs_p"] for s in summary]),
                   (b_pfs_c, [s["med_pfs_c"] for s in summary]),
                   (b_os_p,  [s["med_os_p"]  for s in summary]),
                   (b_os_c,  [s["med_os_c"]  for s in summary])]:
    for bar, v in zip(bars, vals):
        ax_sum.text(bar.get_x() + bar.get_width()/2, v + 0.15,
                    f"{v:.1f}", ha="center", va="bottom",
                    fontsize=8, color=bar.get_facecolor(), fontweight="bold")

# ORR overlay (right axis)
ax2_sum.plot(x, [s["orr_p"] for s in summary], "D-",
             color=NAVY, lw=2.5, ms=10, markeredgecolor="white", markeredgewidth=1.5,
             zorder=5, label="ORR Pritamab (%)")
ax2_sum.plot(x, [s["orr_c"] for s in summary], "s-",
             color=GRAY, lw=1.8, ms=8, markeredgecolor="white", markeredgewidth=1.5,
             zorder=5, label="ORR Control (%)")
for xi, s in enumerate(summary):
    ax2_sum.text(xi, s["orr_p"] + 1.5, f"{s['orr_p']:.0f}%",
                 ha="center", va="bottom", fontsize=9,
                 fontweight="bold", color=NAVY)
    ax2_sum.text(xi - 0.05, s["orr_c"] - 4, f"{s['orr_c']:.0f}%",
                 ha="center", va="top", fontsize=8.5, color=GRAY)

ax_sum.set_xticks(x)
ax_sum.set_xticklabels(
    [f"KRAS {s['allele']}\n(n={s['n_p']+s['n_c']})" for s in summary],
    fontsize=11
)
ax_sum.set_ylabel("Median PFS / OS (months)", fontsize=11)
ax2_sum.set_ylabel("ORR (%)",  fontsize=10, color=NAVY)
ax2_sum.tick_params(axis="y", labelcolor=NAVY)
ax2_sum.set_ylim(0, 90)
ax_sum.set_ylim(0, 38)
ax_sum.set_title("(Summary)  DL-Predicted mPFS / mOS / ORR by KRAS Allele  "
                 "—  Bars: median months  |  Lines: ORR%",
                 fontsize=12, fontweight="bold", color=NAVY, pad=10)
ax_sum.spines[["top","right"]].set_visible(False)

lines1, labs1 = ax_sum.get_legend_handles_labels()
lines2, labs2 = ax2_sum.get_legend_handles_labels()
ax_sum.legend(lines1+lines2, labs1+labs2,
              loc="upper right", fontsize=9, framealpha=0.95,
              facecolor="white", edgecolor="#CBD5E0", ncol=3)

# Footnote
fig.text(0.5, 0.018,
         "DL predictions from Pritamab Multimodal Fusion MLP (Cellpose+RNA-seq+PK/PD+CT).  "
         "Synthetic cohort n=1,000 (seed=2026). KRAS allele freq: G12D 26%, G12V 19%, G12C 12%, G13D 9%, WT 34%.  "
         "Not actual clinical trial data.",
         ha="center", va="bottom", fontsize=7.5, color=GRAY, style="italic")

# Legend (top-right: arm colors)
arm_legend = [
    Line2D([0],[0], color=NAVY, lw=2.5, linestyle="solid",  label="Pritamab arm (solid)"),
    Line2D([0],[0], color=RED,  lw=2.0, linestyle="dashed", label="Control arm (dashed)"),
]
fig.legend(handles=arm_legend, loc="upper right",
           bbox_to_anchor=(0.98, 0.915), fontsize=9.5,
           framealpha=0.95, facecolor="white", edgecolor="#CBD5E0")

plt.savefig(r"f:\ADDS\figures\pritamab_dl_kras_survival.png",
            dpi=200, bbox_inches="tight", facecolor=BG)
print("Saved: pritamab_dl_kras_survival.png")
plt.close()
